#!/usr/bin/env python

from __future__ import print_function
import sys
import json

data = json.load(sys.stdin)
tests = sys.argv[1:]

total = True
for test in tests:
    result = bool(eval(test, {}, {'json': data}))
    print("json> (%s) == %s" % (test, 'TRUE' if result is True else 'FALSE'))
    total = total and result

if total:
    sys.exit(0)
else:
    sys.exit(1)
